Re-pill/RePill_BE

src/main/java/com/repill/backend/RePillApplication.java, src/main/java/com/repill/backend/common/entity/BaseEntity.java, src/main/java/com/repill/backend/discardrecord/entity/DiscardRecord.java, src/main/java/com/repill/backend/medicine/entity/Medicine.java, src/main/java/com/repill/backend/medicine/entity/MedicineType.java, src/main/java/com/repill/backend/medicineboxarea/entity/LocationType.java, src/main/java/com/repill/backend/medicineboxarea/entity/MedicineBoxArea.java, src/main/java/com/repill/backend/member/entity/Member.java, src/main/java/com/repill/backend/member/entity/Member_Location.java, src/main/java/com/repill/backend/member/entity/Rank.java
> 작성된 ERD를 토대로 엔티티 클래스를 설계 및 구현했습니다.
> 알림 엔티티는 배제하고 구현하였고, 객체 생성자는 구현하지 않았습니다.
> close #1 
<br>
=> ✨ Feat: 엔티티 클래스 설계 및 구현

build.gradle, src/main/java/com/repill/backend/apiPayload/ApiResponse.java, src/main/java/com/repill/backend/apiPayload/code/BaseCode.java, src/main/java/com/repill/backend/apiPayload/code/BaseErrorCode.java, src/main/java/com/repill/backend/apiPayload/code/ErrorReasonDTO.java, src/main/java/com/repill/backend/apiPayload/code/ReasonDTO.java, src/main/java/com/repill/backend/apiPayload/code/status/ErrorStatus.java, src/main/java/com/repill/backend/apiPayload/code/status/SuccessStatus.java, src/main/java/com/repill/backend/apiPayload/exception/ExceptionAdvice.java, src/main/java/com/repill/backend/apiPayload/exception/GeneralException.java, src/main/java/com/repill/backend/apiPayload/exception/handler/TestHandler.java, src/main/java/com/repill/backend/medicineboxarea/entity/LocationType.java, src/main/java/com/repill/backend/member/entity/Rank.java, src/main/java/com/repill/backend/test/TestController.java, src/main/java/com/repill/backend/test/TestConverter.java, src/main/java/com/repill/backend/test/TestService.java, src/main/java/com/repill/backend/test/dto/TestRequest.java, src/main/java/com/repill/backend/test/dto/TestResponse.java, src/main/resources/application.yml
> API 응답 통일 정의, 에러 핸들러를 추가했습니다.
> test 디렉토리를 참고해주세요
> 
> 이 PR과 연관된 이슈 번호를 작성하세요. 예) close #3 
<br>
=> ✨ Feat: API 응답 통일, 에러 핸들러 추가

build.gradle, src/main/java/com/repill/backend/global/configuration/SwaggerConfig.java, src/main/java/com/repill/backend/test/TestController.java, src/main/resources/application.yml
> Swagger 세팅 완료했습니다. 사용 예시는 test 패키지를 확인해주세요.
> 
> close #6 
<br>
=> ✨ Feat: Swagger 세팅

src/main/java/com/repill/backend/apiPayload/code/status/ErrorStatus.java, src/main/java/com/repill/backend/medicine/controller/MedicineController.java, src/main/java/com/repill/backend/medicine/dto/MedicineRequest.java, src/main/java/com/repill/backend/medicine/dto/MedicineResponse.java, src/main/java/com/repill/backend/medicine/entity/Medicine.java, src/main/java/com/repill/backend/medicine/entity/MedicineType.java, src/main/java/com/repill/backend/medicine/repository/MedicineJpaRepository.java, src/main/java/com/repill/backend/medicine/repository/MedicineTypeJpaRepository.java, src/main/java/com/repill/backend/medicine/service/DataInitializer.java, src/main/java/com/repill/backend/medicine/service/MedicineService.java, src/main/java/com/repill/backend/member/entity/Member.java, src/test/java/com/repill/backend/medicine/entity/MedicineTest.java, src/test/java/com/repill/backend/medicine/service/MedicineServiceTest.java
> 해당 PR에서 작업한 내용을 간결하게 정리해주세요.
> 
> close #7 
<br>
=> ✨ Feat: 약품 등록 기능 구현

src/main/java/com/repill/backend/member/entity/MemberLocation.java
=> ♻️ Refactor: MemberLocation 클래스명 리팩토링

src/main/java/com/repill/backend/apiPayload/code/status/ErrorStatus.java, src/main/java/com/repill/backend/medicine/controller/MedicineController.java, src/main/java/com/repill/backend/medicine/dto/MedicineResponse.java, src/main/java/com/repill/backend/medicine/entity/Medicine.java, src/main/java/com/repill/backend/medicine/repository/MedicineJpaRepository.java, src/main/java/com/repill/backend/medicine/service/DataInitializer.java, src/main/java/com/repill/backend/medicine/service/MedicineService.java, src/main/java/com/repill/backend/member/repository/MemberJpaRepository.java, src/test/java/com/repill/backend/medicine/service/MedicineServiceTest.java
> 약품 디데이 리스트 조회 기능과 약품 디테일 조회 기능 구현, 테스트 코드를 작성했습니다.
> 
> close #10 
<br>
=> ✨ Feat: 약품 조회 기능 추가

build.gradle, src/main/java/com/repill/backend/apiPayload/code/status/ErrorStatus.java, src/main/java/com/repill/backend/apiPayload/code/status/SuccessStatus.java, src/main/java/com/repill/backend/apiPayload/exception/RePillClientException.java, src/main/java/com/repill/backend/apiPayload/exception/RePillException.java, src/main/java/com/repill/backend/global/configuration/SecurityConfig.java, src/main/java/com/repill/backend/global/configuration/SwaggerConfig.java, src/main/java/com/repill/backend/global/configuration/WebConfig.java, src/main/java/com/repill/backend/global/security/authDTO/AuthRequestDTO.java, src/main/java/com/repill/backend/global/security/authDTO/AuthResponseDTO.java, src/main/java/com/repill/backend/global/security/authDTO/KakaoProfile.java, src/main/java/com/repill/backend/global/security/authDTO/OAuthToken.java, src/main/java/com/repill/backend/global/security/controller/AuthController.java, src/main/java/com/repill/backend/global/security/controller/AuthService.java, src/main/java/com/repill/backend/global/security/conveter/AuthConverter.java, src/main/java/com/repill/backend/global/security/filter/JwtRequestFilter.java, src/main/java/com/repill/backend/global/security/handler/annotation/AuthUser.java, src/main/java/com/repill/backend/global/security/handler/resolver/AuthUserArgumentResolver.java, src/main/java/com/repill/backend/global/security/principal/PrincipalDetails.java, src/main/java/com/repill/backend/global/security/principal/PrincipalDetailsService.java, src/main/java/com/repill/backend/global/security/provider/JwtTokenProvider.java, src/main/java/com/repill/backend/global/security/provider/KakaoAuthProvider.java, src/main/java/com/repill/backend/member/repository/MemberRepository.java, src/main/java/com/repill/backend/test/TestController.java, src/main/java/com/repill/backend/token/domain/Token.java, src/main/java/com/repill/backend/token/repository/TokenRepository.java, src/main/java/com/repill/backend/token/service/TokenService.java, src/main/resources/application.yml
> 카카오 소셜 로그인을 구현했습니다. 사용 예시는 test 패키지와 API 명세 문서를 확인해주세요
> 
> 이 PR과 연관된 이슈 번호를 작성하세요. 예) close #5 
<br>
=> ✨ Feat: 카카오 소셜 로그인 구현

src/main/java/com/repill/backend/discardrecord/repository/DiscardRecordRepository.java, src/main/java/com/repill/backend/medicine/repository/MedicineJpaRepository.java, src/main/java/com/repill/backend/member/controller/MemberController.java, src/main/java/com/repill/backend/member/converter/MemberConverter.java, src/main/java/com/repill/backend/member/dto/MemberResponse.java, src/main/java/com/repill/backend/member/entity/Member.java, src/main/java/com/repill/backend/member/memberService/MemberService.java
> 회원 정보 조회 API 를 구현했습니다.
> Member 엔티티의 필드 기본값 설정이 필요한 곳을 수정했습니다
>
> 이 PR과 연관된 이슈 번호를 작성하세요. 예) close #19 
<br>
=> ✨ Feat: 회원 정보 조회 API 구현

src/main/java/com/repill/backend/apiPayload/code/status/ErrorStatus.java, src/main/java/com/repill/backend/discardrecord/controller/DiscardRecordController.java, src/main/java/com/repill/backend/discardrecord/dto/DiscardRecordRequest.java, src/main/java/com/repill/backend/discardrecord/dto/DiscardRecordResponse.java, src/main/java/com/repill/backend/discardrecord/entity/DiscardRecord.java, src/main/java/com/repill/backend/discardrecord/repository/DiscardRecordJpaRepository.java, src/main/java/com/repill/backend/discardrecord/service/DiscardRecordService.java, src/main/java/com/repill/backend/medicine/controller/MedicineController.java, src/main/java/com/repill/backend/medicine/entity/Medicine.java, src/main/java/com/repill/backend/medicine/repository/MedicineJpaRepository.java, src/main/java/com/repill/backend/medicine/service/DataInitializer.java, src/main/java/com/repill/backend/medicine/service/MedicineService.java, src/main/java/com/repill/backend/medicineboxarea/entity/MedicineBoxArea.java, src/main/java/com/repill/backend/medicineboxarea/repostory/MedicineBoxAreaJpaRepository.java, src/test/java/com/repill/backend/discardrecord/entity/DiscardRecordTest.java, src/test/java/com/repill/backend/discardrecord/service/DiscardRecordServiceTest.java, src/test/java/com/repill/backend/medicine/service/MedicineServiceTest.java
> 약품 폐기 기록을 등록하는 기능을 구현했습니다.
> 
> close #16 
<br>
=> ✨ Feat: 약품 폐기 기록 등록 기능 추가

src/main/java/com/repill/backend/apiPayload/code/status/ErrorStatus.java, src/main/java/com/repill/backend/discardrecord/controller/DiscardRecordController.java, src/main/java/com/repill/backend/discardrecord/dto/DiscardRecordResponse.java, src/main/java/com/repill/backend/discardrecord/repository/DiscardRecordJpaRepository.java, src/main/java/com/repill/backend/discardrecord/service/DiscardRecordService.java, src/test/java/com/repill/backend/discardrecord/service/DiscardRecordServiceTest.java
> 폐의약품 폐기 인증 리스트 조회, 폐의약품 폐기 인증 디테일 조회 기능을 구현했습니다.
> 
> close #26 
<br>
=> ✨ Feat: 약품 폐기 인증 정보 조회 기능 추가

src/main/java/com/repill/backend/discardrecord/controller/DiscardRecordController.java, src/main/java/com/repill/backend/medicine/repository/MedicineTypeJpaRepository.java, src/main/java/com/repill/backend/medicine/service/DataInitializer.java, src/main/java/com/repill/backend/member/controller/MemberController.java, src/main/java/com/repill/backend/member/converter/MemberConverter.java, src/main/java/com/repill/backend/member/dto/MemberResponse.java, src/main/java/com/repill/backend/member/memberService/MemberService.java, src/main/resources/application.yml
>  폐기한 약품 종류 통계 API를 추가했습니다.
> 누락된 의약품 타입을 추가했습니다
> DiscardRecordController의 Swagger 설명을 추가로 작성했습니다.
> 
> 이 PR과 연관된 이슈 번호를 작성하세요. 예) close #28 
<br>
=> ✨ Feat: 폐기한 약품 종류 통계 추가 

src/main/java/com/repill/backend/medicineboxarea/controller/MedicineBoxAreaController.java, src/main/java/com/repill/backend/medicineboxarea/dto/MedicineBoxAreaResponse.java, src/main/java/com/repill/backend/medicineboxarea/service/MedicineBoxAreaService.java, src/test/java/com/repill/backend/medicineboxarea/service/MedicineBoxAreaServiceTest.java
> 폐의약품 수거함을 지도에 마커로 표시하는 기능을 구현했습니다.
> 
> close #33 
<br>
=> ✨ Feat: 폐의약품 수거함 마커 표시 기능

src/main/java/com/repill/backend/medicine/controller/MedicineController.java
> /api/medicines/d-day/{memberId} -> /api/medicines/d-day/ 엔드 포인트를 변경했습니다.
> 
> close #36 
<br>
=> ♻️ Refactor: 약품 폐기 리마인드 디데이 리스트 조회 엔드 포인트 수정

build.gradle, src/main/java/com/repill/backend/discardrecord/controller/DiscardRecordController.java, src/main/java/com/repill/backend/discardrecord/dto/DiscardRecordRequest.java, src/main/java/com/repill/backend/discardrecord/entity/DiscardRecord.java, src/main/java/com/repill/backend/discardrecord/service/AzureBlobService.java, src/main/java/com/repill/backend/discardrecord/service/DiscardRecordService.java, src/main/java/com/repill/backend/global/configuration/AzureBlobConfig.java, src/main/resources/application.yml, src/test/java/com/repill/backend/discardrecord/entity/DiscardRecordTest.java, src/test/java/com/repill/backend/discardrecord/service/DiscardRecordServiceTest.java
> 이미지 파일 저장 기능을 구현헀습니다.
> 
> close #39 
<br>
=> ✨ Feat: Azure blob storage 서비스 추가

src/main/java/com/repill/backend/domain/discardrecord/controller/DiscardRecordController.java, src/main/java/com/repill/backend/global/configuration/SecurityConfig.java, src/main/resources/application.yml
> CORS 설정에 프론트엔드 도메인을 추가했습니다.
> createDiscardRecord 컨트롤러 파라미터를 수정했습니다
> close #44 
<br>
=> ✨ Feat: 프론트엔드 도메인 COR 설정

src/main/java/com/repill/backend/global/configuration/SecurityConfig.java
=> ✨ Feat: CORS 설정 수정

src/main/java/com/repill/backend/domain/medicineboxarea/controller/MedicineBoxAreaController.java, src/main/java/com/repill/backend/domain/medicineboxarea/service/MedicineBoxAreaService.java
=> 🐛 Fix: 폐의약품 수거함 위치 마커 표기 기능 수정

src/main/java/com/repill/backend/domain/medicineboxarea/service/MedicineBoxAreaService.java
> 해당 PR에서 작업한 내용을 간결하게 정리해주세요.
> 코드 리뷰 시 참고할 만한 사항이나 주의할 점을 작성해주세요.
> 이 PR과 연관된 이슈 번호를 작성하세요. 예) close #10
<br>
=> 🐛 Fix: 반경 10km로 수정

src/main/java/com/repill/backend/domain/medicineboxarea/service/MedicineBoxAreaService.java, src/test/java/com/repill/backend/medicineboxarea/service/MedicineBoxAreaServiceTest.java
> 해당 PR에서 작업한 내용을 간결하게 정리해주세요.
> 코드 리뷰 시 참고할 만한 사항이나 주의할 점을 작성해주세요.
> 이 PR과 연관된 이슈 번호를 작성하세요. 예) close #10
<br>
=> ✅ Test: 테스트 코드 수정

src/main/java/com/repill/backend/domain/medicineboxarea/service/MedicineBoxAreaService.java, src/test/java/com/repill/backend/medicineboxarea/service/MedicineBoxAreaServiceTest.java
=> 🐛 Fix: 반경 3km로 수정
